name: flutter_to_do
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^0.2.0

  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  injectable: ^2.0.1
  get_it: ^7.2.0
  auto_route: ^5.0.4
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.5
  dartz: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  injectable_generator: ^2.0.1
  auto_route_generator: ^5.0.3
  isar_generator: ^3.0.5
  mockito: ^5.3.2
  flutter_lorem: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
